---
# This playbook prints a simple debug message
- name: Echo Hello, world!
  hosts: localhost
  
  tasks:
  - debug: msg="Hello, world!"
  - shell: sleep '{{ sleep | default(0) }}'
  - debug: msg="Bye, world!"
